export const generateStudyPlan = async (userGoal) => {
    console.log('Mock Gemini API Call:', userGoal);
    // TODO: Implement actual Gemini API call
    return Promise.resolve("This is a mock study plan generated by Gemini.");
};
